### ISSUE TITLE
Allow correlations between grid and single time series

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esm_analysis#29]
This might be an issue for `climpred`, but I want to be able to correlate a grid of data with a single time series. Currently if you give it a grid for x, it wants the same grid for y.

**Comment by bradyrx** [comment]
Might just do it in `esmtools`, since it isn't needed for `climpred` functionality. A hacky/simple way is to just force-broadcast the single time series to the same shape as the grid:

```python
import numpy as np
import xarray as xr

x = xr.DataArray(np.random.rand(100,10,10), dims=['time', 'lat', 'lon'])
x['lon'] = np.linspace(0, 27, 10)
x['lat'] = np.linspace(-15, 12, 10)
# This can't be correlated currently since it's not the same grid size.
y = xr.DataArray(np.random.rand(100), dims=['time'])

# Force up to the same size as the x grid.
y = xr.concat([y]*10, 'lat')
y = xr.concat([y]*10, 'lon')
y['lat'] = x['lat']
y['lon'] = x['lon']

# Now this works.
et.stats.corr(x, y)
```

**Comment by aaronspring** [comment]
You can also just use x,y = xr.broadcast(x,y)

**Comment by bradyrx** [comment]
Ah, nice. That's much more concise.

**Comment by bradyrx** [comment]
Still need to implement the broadcast into an actual function so one doesn't have to do this manually.

**Comment by bradyrx** [comment]
Addressed in https://github.com/bradyrx/esm_analysis/pull/58
