### ISSUE TITLE
Regional analysis and masking

### ISSUE THREAD

**Issue by aaronspring** [bradyrx/esm_analysis#4]
I guess you do regional analysis by taking a map, selections a Lon lat range and then take a weighted average. 

What about using regionmask or salem for selection of regions. Here we could select based on shapefiles for non-rectangular shapes and so on.
I envision a shape file configuration that I just need to apply to a map to get averages oder sum of many different ocean basins or land areas based on a before configured shapefile/mask

https://regionmask.readthedocs.io/en/stable/_static/notebooks/mask_xarray.html but I here I find no oceans but it should work with any shapefiles also

https://salem.readthedocs.io/en/latest/xarray_acc.html

What do you think about it?

**Comment by bradyrx** [comment]
@aaronspring, for eventually loading these masks (and other sample datasets) I took `xarray's` load_dataset function and added some features for us. This might be helpful for `climpred` as well.

See here: https://github.com/bradyrx/esmtools/blob/master/esmtools/loadutils.py. It only uses `xarray` internals, os, etc. You can submit a url to any github repo, however the file needs to be `*.md5`. I opened a repository under here: https://github.com/bradyrx/climdata where we can host NetCDF masks and sample data (can add subfolders in the future). All you need to do is clone the repo and run the python script within it to convert netCDFs into .md5.

If we desire larger files than 100mb each in the future, we should look into this: https://git-lfs.github.com/

Lastly, here's a demo of how easy it is:
---
![](https://i.imgur.com/uGLeyYN.png)

**Comment by bradyrx** [comment]
A possible package for regridding: https://xesmf.readthedocs.io/en/latest/why.html. I find NCO and CDO remapping to be difficult, but maybe it's less complicated than I think.

**Comment by aaronspring** [comment]
I once tried xesmf and then switched back to cdo after a minute.

**Comment by aaronspring** [comment]
Thats how I do it usually. But I am also open to the xesmf implementation.
Here you can also use multiple cores `(options='-P')` to speed up (which helps if you remap a lon lat depth time file).

```python
import cdo
cdo = cdo.Cdo()
def cdo_remap(ds,outputgrid='r360x180',options=''):
    """
    Remap using cdo's remapbil.

    Documentation: https://code.mpimet.mpg.de/projects/cdo/embedded/index.html#x1-5810002.12.1
    """
    remapped = cdo.remapbil(outputgrid,input=ds,options=options)
    return xr.open_dataset(remapped)

%time cdo_remap(control3d)
%time cdo_remap(control3d,options='-P 4')

**Comment by bradyrx** [comment]
Thanks for the code snippet. I'm having trouble with CDO on my personal laptop right now... issues with loading netCDF files. 

I think we should use CDO/NCO for remapping because they are much more powerful, and both now have python wrappers. In particular, xESMF is limited in the types of grids it can switch between.

NCO/CDO can remap to triangular and hexagonal meshes as well as unstructured meshes (which is helpful for the simulation I'm running on MPAS, which is unstructured).

**Comment by bradyrx** [comment]
A great resource for lots of ocean shapefiles if we decide to use `salem` down the line:
http://www.marineregions.org/sources.php

Just need to figure out how to coarsen the shape files a little since they're at ~110m resolution.

**Comment by aaronspring** [comment]
Did you get to solution for you on this?

What do you think about 
https://github.com/bradyrx/esmask/pull/4 ?

**Comment by bradyrx** [comment]
@aaronspring, I think your solution is good. I should try it out on some CESM output and especially on my unstructured grid (MPAS) to see if it works.

I got it to work really fast with cython here: https://github.com/bradyrx/esmask/blob/f3b24140eaaedd729f66d1bee18cbb14dbb30637/notebooks/working_cython_mask.ipynb

Although it depends on a step where you build up a huge list of all of the grid cell points as geopandas objects. Once that's built, it can run the mask in less than a few seconds. But for my unstructured high-resolution mesh, it was taking a super long time just to build the point list.

Anyways, I think you're solution is good. I'll try the LME or EEZ mask on both CESM and MPAS when I get a chance before we implement it. But I view `esmask` as more of a repository for masks once they're made. I don't think we need a really nice set of functions to do this... more of notebooks to guide us through the process. Ideally you only mask your model and resolution once and then keep pulling from that.

**Comment by bradyrx** [comment]
Note that I was able to get regridding working well (which we were talking about in this thread). I used NCL to go from 1 degree x 1 degree to the POP curvilinear grid, for example, for both conservative and bilinear interpolation. 

Here's the NCL documentation and there's a bunch of example scripts out there: https://www.ncl.ucar.edu/Document/Functions/ESMF/ESMF_regrid.shtml

I'm just going to make NCL scripts for the regridding because it works well.

**Comment by aaronspring** [comment]
as a reference: https://esmlab.readthedocs.io/en/latest/

**Comment by aaronspring** [comment]
does this need to be open? for me, regionmask works very well!

**Comment by bradyrx** [comment]
This has a ton of good references. It really just depends on what sort of masking you need to do, but I agree `regionmask` does the trick for most cases.
