### ISSUE TITLE
Add pattern correlation

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esm_analysis#46]
As in, something like this: https://www.ncl.ucar.edu/Document/Functions/Contributed/pattern_cor.shtml

**Comment by aaronspring** [comment]
how is this different that a simple correlation?
```python
from xskillscore import pearson_r
# 3d input
corr = pearson_r(c,c2,'time')
corr.plot()
<matplotlib.collections.QuadMesh at 0x11ee16c88>

# 2d input
# select non nan region
corr2 = pearson_r(c.mean('time').sel(x=slice(100,120),y=slice(50,75)),c2.mean('time').sel(x=slice(100,120),y=slice(50,75)),['y','x'])
corr2
<xarray.DataArray ()>
array(-0.810549, dtype=float32)

**Comment by bradyrx** [comment]
I forgot about @ahuang11's implementation of the spatial correlation. I imagine this would be the same as a "pattern correlation." I think this handles exactly what I need. I imagine it just compresses both grids down to a single vector and correlates along that vector as if it were a time series.
