### ISSUE TITLE
Fourier transforms

### ISSUE THREAD

**Issue by bradyrx** [bradyrx/esm_analysis#47]
Might be nice to wrap some of these functions for spectral analysis: https://xrft.readthedocs.io/en/latest/#

I haven't done anything with `xrft` yet, but it's an `xarray` wrapper for fourier transforms.

**Comment by aaronspring** [comment]
isnt `xrft` already quite wrapped, ie. generalized but not specific to a certain model output format? the same way we discussed this with the `eofs.xarray` package?

**Comment by bradyrx** [comment]
I figured it is. I haven't touched it at all. This was more of a reminder for me to check out this package. I imagine I won't have to implement anything.
